# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ features ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted
    steps:
    - name: Step 1 - Checkout main branch from GitHub
      uses: actions/checkout@v3
    - name: Step 2 - Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin' # See 'Supported distributions' for available options
        cache: maven
    
    - name: Step 3 - Build package Maven
      run: mvn -B package --file pom.xml

